### ISSUE TITLE
documentation up-to-date for RaspberryPi?

### ISSUE THREAD

**Issue by saveriogzz** [goeh/weather-collector#2]
Hi Goran,

I'm trying to use the library on a RaspberryPi, is the documentation still up-to-date for this use case?

I tried to follow the steps on the README file but the only executable in the bin folder is `download` (not `weather-collector`) as indicated. Also, it looks like `collector.properties` is now called `datastore.properties`.

Is there any change you could give some indications on how to proceed?

I'm definitely willing to contribute to the project (not a Java expert yet but willing to learn!)

Thanks

**Comment by goeh** [comment]
I'm sorry but the docs are probably outdated. But a fun coincidence is that yesterday I bought a new Davis Vantage Pro2+ weather station. My current is from 2005 and still in use, awesome quality!
I will replace the weather station hopefully the coming weekend, and then I will also reinstall the software on a new Raspberry Pi and update the documentation.
Thanks for showing interest in the project. I will update this issue in a week.

**Comment by saveriogzz** [comment]
this is great!! my project will involve also some data streaming using apache Pulsar. Please let me know if there is any interest in adding an apache pulsar producer/client to the project!

Thanks a lot

**Comment by goeh** [comment]
I've updated the documentation (README) now. Please check it out and provide feedback when you have some time.
Thanks!

**Comment by saveriogzz** [comment]
Hi @goeh ! Thanks a lot for merging #3 .

About the documentation, I am having troubles starting the program because I receive a java exception:

```bash
$ ./bin/weather-collector-1.4.2 $SERIAL_PORT $SERIAL_BAUD
Exception in thread "main" java.lang.UnsatisfiedLinkError: jssc/SerialNativeInterface.openPort(Ljava/lang/String;Z)J
	at jssc.SerialPort.openPort(SerialPort.java:158)
	at se.technipelago.weather.vantagepro.AbstractController.startLocal(AbstractController.java:93)
	at se.technipelago.weather.vantagepro.DownloadController.main(DownloadController.java:59)
```

My Davis console is connected to my RPi 4 through USB and I'm using the default parameters `SERIAL_PORT=/dev/ttyUSB0` and `SERIAL_BAUD=19200`.
The issue is probably deriving by the library `jssc`, but I cannot find the reason. Is it working for you?

Thanks

**Comment by goeh** [comment]
Yes, it's working for me. But I do run on Raspbian, both old versions and the latest (2021-05-07).

Is /dev/ttyUSB0 available and readable by your user?
On my Raspberry Pi 3 I did not have to do anything special, I just followed the instructions and data was downloaded, but it took 10 minutes first time.

**Comment by goeh** [comment]
I don't know but maybe you have to install som extra packages on Ubuntu, like libjssc-java.
Or maybe jssc is not compatible with Raspberry Pi 4.
I have a spare Raspberry Pi 4. I can try to install it on that, if I find some time this evening.

**Comment by goeh** [comment]
Make sure use the start script created by the gradle application plugin. The scripts are located in build/scripts, or in the bin folder when you extract the .zip archive. The start script configures Java classpath with all the required libraries (including jssc-2.8.0.jar).

**Comment by saveriogzz** [comment]
> I don't know but maybe you have to install som extra packages on Ubuntu, like libjssc-java.
> Or maybe jssc is not compatible with Raspberry Pi 4.

This is the issue indeed! I found [this](https://github.com/java-native/jssc/releases/tag/v2.9.4) to be compatible!
Although I received a `SEVERE` warning (see below), it seems now to be running for its first time!

```bash
Sep 20, 2021 2:35:43 PM se.technipelago.weather.archive.SqlDataStore init
SEVERE: Cannot connect to database
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
```

I will keep you up-to-date, thanks a ton @goeh !

**Comment by goeh** [comment]
My current installation uses the old MySQL driver, and my collector.properties looks like this:

```
datastore.type=jdbc
datastore.name=weather
datastore.jdbc.driver=com.mysql.jdbc.Driver
datastore.jdbc.url=jdbc:mysql://localhost:3306/weather?user=username&password=password
```
In your case the driver is `com.mysql.cj.jdbc.Driver`, and maybe you need to specify some extra parameters on the url for MySQL 8. Like disable TLS or something...

**Comment by saveriogzz** [comment]
Thanks @goeh !
I will close this for now so not to risk to go off-topic with the issue title.

I just sent the PR #4 , let me know what you think!

Cheers
