### ISSUE TITLE
method getLastRecordTime called before tables creation

### ISSUE THREAD

**Issue by saveriogzz** [goeh/weather-collector#9]
I noticed that the method here referenced 

https://github.com/goeh/weather-collector/blob/a3d8af143de92830ccd4bffac053c40b36c94cc5/src/main/java/se/technipelago/weather/archive/SqlDataStore.java#L190

is called before the creation of the SQL tables. The application works fine in case the tables are already created into the database, but it gives errors in case the database has no tables!

**Comment by goeh** [comment]
That sounds like a bug to me

**Comment by goeh** [comment]
The original code calls init() that calls DataStore.init() and the tables are created.
https://github.com/goeh/weather-collector/blob/e49b678cd63a93167e93199fc44f39207ee431e2/src/main/java/se/technipelago/weather/vantagepro/DownloadController.java#L69
Maybe you bypassed the init() code in your changes?

**Comment by goeh** [comment]
But I see what you mean. If `datastore.type` is set to a custom value, the SQL datastore is not initialized.
That store should always be initialized since it's a core data store.
